//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int SoLuongNhapToiThieu { get; set; }
        public int SoLuongTonToiThieu { get; set; }
        public int SoLuongTonToiDa { get; set; }
        public Nullable<int> SoTienNoToiDa { get; set; }
        public string ApDungQD4 { get; set; }
    }
}
